server:
  port: 8888

spring:
  application:
    name: balancer
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/api'

zuul:
  ribbon-isolation-strategy: thread
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 5000
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          timeout:
            enabled: false


transactionservice:
  ribbon:
    eureka:
      enabled: true
    ConnectTimeout: 10000
    ReadTimeout: 10000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100


