server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${server.port}